[package]
name = "http_efi"
version = "0.1.0"
authors = ["Gurinder Singh <gurinder.singh@1e.com>"]

[dependencies]
# efi = { git = "https://github.com/gurry/efi"}
efi = { path = "../efi"}
# http = "*"

[dependencies.httparse]
version = "1.2.4"
default-features = false